### ISSUE TITLE
Existing work item retrieval ignores filtering on target project

### ISSUE THREAD

**Issue by ArjayHawco** [Microsoft/vsts-work-item-migrator#51] opened 2019-02-14 18:03 UTC
Note: This item is similar to issue #47 "Querying for already existing work items seems to ignore project".

To repro:
1) We are migrating from on-premise TFS to Azure DevOps.
2) Set the post-move-tags the config file to empty and set the skip-existing param to false
3) Create a test (i.e. Test) Azure DevOps project
4) Create a query to use in the on-premise TFS project that migrates 1/3 the work items
5) Run the migration tool to migrate the items into the Test Azure project (notice the # of existing items display as 0 in the target project during the migration)
6) Create a final (i.e. Final) Azure DevOps project
7) Update the query in TFS to migrate all the items
8) Run the migration tool again on the Final Azure project (notice how the # of existing items display as the 1/3 amount in the target project during the migration)

Expected behavior:
The migration tool should read any existing migrated work items from the target project only (as opposed to any work items in the target Azure DevOps organization)

Actual behavior:
The migration tool appears to be reading work items from any project (e.g. the Test) project rather than the target project (e.g. Final)

**Comment by sferg-msft** [comment] 2019-04-27 16:23
When this tool was originally written, work items only had account scoped URLs.  We now have project scoped URLs, so I coud consider that enhancement.  It would have to be opt in, since it would break anything that was previously migrated using the collection scoped URLs.

**Comment by sferg-msft** [comment] 2019-04-27 16:28
Closing as a dupe of #47

**Closed by sferg-msft** 2019-04-27 16:28 UTC
Labels: duplicate, enhancement
